#ifndef CHAPPIEFIRMWARE_PINOUT_H
#define CHAPPIEFIRMWARE_PINOUT_H

#define MULTIPLEXER_ADDR 0x70
#define ENCODER_ADDR 0x36

#define LATCH_PIN 23
#define CLOCK_PIN 19
#define DATA_PIN 25

#define JOYSTICK_PIN_1 32
#define JOYSTICK_PIN_2 33
#define JOYSTICK_PIN_3 35
#define JOYSTICK_PIN_4 36
#define JOYSTICK_PIN_5 34
#define JOYSTICK_PIN_6 39

#define AXIS_1_PUL_PIN 12
#define AXIS_2_PUL_PIN 18
#define AXIS_3_PUL_PIN 16
#define AXIS_4_PUL_PIN 5
#define AXIS_5_PUL_PIN 23
#define AXIS_6_PUL_PIN 17

#define ENDSTOP_1_PIN 4
#define ENDSTOP_2_PIN 13
#define ENDSTOP_3_PIN 14
#define ENDSTOP_4_PIN 15
#define ENDSTOP_5_PIN 26
#define ENDSTOP_6_PIN 27

#endif //CHAPPIEFIRMWARE_PINOUT_H
